### ISSUE TITLE
Repeated rest parameter

### ISSUE THREAD

**Issue by roddolf** [CarbonLDP/carbonldp-ts-docs-engine#20]
When a rest parameter is declared in a method, it is rendered twice inside the parameter table.

For example, in `sparqler/clauses/SelectClause#select()`:
![image](https://user-images.githubusercontent.com/14943928/70822938-58cea080-1da4-11ea-94cb-ff5c69f71c89.png)

**Comment by inakijaneiro** [comment]
This is expected behavior if the documentation is written as `@param variables`. To fix this, you should document it as `@param ...variables`.
