### ISSUE TITLE
Fix link tag to methods

### ISSUE THREAD

**Issue by roddolf** [CarbonLDP/carbonldp-ts-docs-engine#9]
Currently adding a link tag (`{@link }`) to a method will generate a link with a text that only has the class/interface but not the method name.

This is due to the package `dgeni-packages/typescript`, generate the methods alias without following the alias templates and adding an index to that method; making the service `getLinkInfo` (of package `dgeni-packages/links`), to fail in finding the corresponding document.

We can consider al least 2 options:
- Implement a custom links service
- Change how aliases are generated to match the current link service

**Comment by inakijaneiro** [comment]
Perhaps this isn't the expected behavior of dgeni. We should wait until angular/dgeni-packages#285 has an answer.
